### ISSUE TITLE
Dossiers "internes" mis en exergue

### ISSUE THREAD

**Issue by SnarkBoojum** [MaTsou/Commission_CPGE#1]
Parmi les dossiers notés comme "à voir" (ie: avec un signal d'admin), il faudrait mettre tous les dossiers de l'établissement.

**Comment by MaTsou** [comment]
Salut,
je viens de voir cette suggestion de ta part... J'ai bien peur de ne pas comprendre. Peux-tu préciser?

**Comment by SnarkBoojum** [comment]
L'idée est que certains dossiers sont signalés à la commission avec une couleur parce qu'ils ont quelque chose de spécial qui nécessite une attention particulière (ça existe déjà, je ne sais plus pourquoi) ; et je suggère ici de faire en sorte que les dossiers de terminale qui viennent de chez nous soient ainsi mis en avant.

**Comment by MaTsou** [comment]
C'est une très bonne idée... Je vois ça.
